import { Link, useNavigate } from "react-router-dom";
import { Minus, Plus, Trash2 } from "lucide-react";
import Navbar from "../components/common/Navbar.jsx";
import Footer from "../components/common/Footer.jsx";
import { Button, EmptyState } from "../components/common/ui.jsx";
import { useCart } from "../context/CartContext.jsx";

export default function Cart() {
  const { items, removeItem, setQuantity, total } = useCart();
  const navigate = useNavigate();
  const delivery = items.length ? 0 : 0;
  return <div className="min-h-screen bg-canvas text-ink dark:bg-night dark:text-white"><Navbar /><main className="page-wrap pt-28 pb-16"><h1 className="text-3xl font-black">Your cart</h1>{!items.length ? <EmptyState className="mt-8" title="Your cart is empty." text="Discover fresh produce from farmers and FPOs." action={<Link to="/marketplace"><Button>Explore Marketplace</Button></Link>} /> : <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-3">{items.map((item) => <div key={item.id} className="flex gap-4 rounded-2xl border border-slate-200 bg-white p-4 dark:border-white/10 dark:bg-panel"><img src={item.image} alt={item.cropName} className="h-24 w-24 rounded-xl object-cover" /><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><div><h2 className="font-bold">{item.cropName}</h2><p className="text-sm text-slate-500">₹{item.price} / {item.unit} · {item.location}</p></div><button type="button" aria-label={`Remove ${item.cropName}`} onClick={() => removeItem(item.id)} className="text-slate-400 hover:text-rose-500"><Trash2 className="h-4 w-4" /></button></div><div className="mt-4 inline-flex items-center gap-3 rounded-lg border border-slate-200 px-2 py-1 dark:border-white/10"><button type="button" aria-label="Decrease quantity" onClick={() => setQuantity(item.id, Math.max(1, item.quantity - 1))}><Minus className="h-4 w-4" /></button><span className="min-w-16 text-center text-sm">{item.quantity} {item.unit}</span><button type="button" aria-label="Increase quantity" onClick={() => setQuantity(item.id, item.quantity + 1)}><Plus className="h-4 w-4" /></button></div></div></div>)}</div><aside className="h-fit rounded-2xl border border-slate-200 bg-white p-5 dark:border-white/10 dark:bg-panel"><h2 className="text-lg font-bold">Order summary</h2><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><span className="text-slate-500">Subtotal</span><span>₹{total.toLocaleString("en-IN")}</span></div><div className="flex justify-between"><span className="text-slate-500">Delivery</span><span>{delivery ? `₹${delivery}` : "Calculated at checkout"}</span></div><div className="border-t border-slate-200 pt-3 text-base font-bold dark:border-white/10"><div className="flex justify-between"><span>Total</span><span>₹{total.toLocaleString("en-IN")}</span></div></div></div><Button className="mt-6 w-full" onClick={() => navigate("/checkout")}>Proceed to Checkout</Button></aside></div>}</main><Footer /></div>;
}
