import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import { ArrowRight, Check, CircleDollarSign, CloudSun, MapPin, PackageCheck, Route, Search, ShieldCheck, Sparkles, Sprout, Truck, Users } from "lucide-react";
import Navbar from "../components/common/Navbar.jsx";
import Footer from "../components/common/Footer.jsx";
import BrandLogo from "../components/common/BrandLogo.jsx";
import HeroMediaCarousel from "../components/common/HeroMediaCarousel.jsx";
import FullBleedHero from "../components/common/FullBleedHero.jsx";
import ReviewsSection from "../components/common/ReviewsSection.jsx";
import { Button } from "../components/common/ui.jsx";
import { publicApi } from "../api/publicApi.js";
import SeoJsonLd from "../seo/SeoJsonLd.jsx";
import { breadcrumbJsonLd, HOME_DESCRIPTION, HOME_TITLE } from "../seo/site.js";

const defaults = {
  heroBadge: "Direct farm-to-market platform", heroHeading: HOME_TITLE, heroSubheading: HOME_DESCRIPTION, heroCtaText: "Get Started", heroCtaLink: "/register", heroSecondaryCtaText: "Explore Marketplace", heroSecondaryCtaLink: "/marketplace", heroMedia: [],
  navMarketplaceLabel: "Marketplace", navHowLabel: "How It Works", navFarmerLabel: "For Farmers", navBuyerLabel: "For Buyers", navReviewsLabel: "Reviews", navAboutLabel: "About",
  features: [{ title: "Fresh listings", text: "From farms and FPOs", icon: "sprout", active: true }, { title: "Clear pricing", text: "Compare before ordering", icon: "price", active: true }, { title: "Order visibility", text: "Track each handoff", icon: "package", active: true }, { title: "Secure by design", text: "Payment-ready checkout", icon: "shield", active: true }],
  howSteps: [{ number: "01", title: "Create your account", text: "Join as a farmer, FPO or buyer." }, { number: "02", title: "List or discover produce", text: "Share supply or find the right listing." }, { number: "03", title: "Connect and place order", text: "Agree on quantity, price and delivery." }, { number: "04", title: "Get produce delivered", text: "Follow the order from pickup to arrival." }],
  marketplaceHeading: "Krishiq Marketplace: Explore fresh produce directly from the source.", marketplaceText: "Search crops, compare available lots, review seller details and place an order from one straightforward agricultural marketplace.",
  farmerHeading: "Sell directly. Reach more buyers.", farmerText: "List produce, manage orders, view market prices and manage deliveries on the Krishiq platform.", farmerBullets: ["List your produce", "Manage orders", "View market prices", "Manage deliveries"], farmerCtaText: "Start Selling", farmerCtaLink: "/register",
  buyerHeading: "Source directly from the farm.", buyerText: "Discover fresh produce, compare listings and track every delivery on the Krishiq agricultural marketplace.", buyerBullets: ["Discover fresh produce", "Compare listings", "Buy required quantities", "Track deliveries"], buyerCtaText: "Explore Produce", buyerCtaLink: "/marketplace",
  insightsHeading: "Krishiq AI: Smart agricultural signals and demand forecasting.", insightsText: "Krishiq AI helps farmers and buyers understand demand trends, price trends, suitable connections and delivery options inside the platform.", insights: [{ title: "Demand trends", text: "Market demand signals", icon: "route" }, { title: "Price trends", text: "Compare current prices", icon: "price" }, { title: "Suitable connections", text: "Find relevant partners", icon: "users" }, { title: "Delivery optimization", text: "Plan each handoff", icon: "truck" }],
  deliveryHeading: "Every handoff stays visible.", deliverySteps: [{ number: "01", title: "Order confirmed", active: true }, { number: "02", title: "Pickup scheduled", active: true }, { number: "03", title: "In transit", active: true }, { number: "04", title: "Delivered", active: true }], aboutHeading: "Connecting farms with markets.", aboutText: "Krishiq is an agritech platform developed by Ankish where farmers, FPOs and buyers connect through one digital marketplace, with tools for listings, orders and deliveries.", ctaHeading: "Make the next market decision simpler.", ctaText: "Join a direct, transparent marketplace for agricultural trade.", contactHeading: "Talk to Krishiq", contactEmail: "hello@krishiq.in", contactPhone: "", contactAddress: "", footerText: "Smart Farming. Direct Markets. Better Future.", copyright: "Connecting farms with markets.", developers: [],
};
const iconMap = { sprout: Sprout, price: CircleDollarSign, package: PackageCheck, shield: ShieldCheck, route: Route, users: Users, truck: Truck };
const reveal = { hidden: { opacity: 0, y: 18 }, show: { opacity: 1, y: 0 } };

export default function Home() {
  const [settings, setSettings] = useState(defaults); const [products, setProducts] = useState([]); const [reviews, setReviews] = useState([]);
  useEffect(() => { Promise.all([publicApi.siteSettings(), publicApi.products(), publicApi.reviews()]).then(([content, listings, publishedReviews]) => { setSettings({ ...defaults, ...content }); setProducts(listings.slice(0, 3)); setReviews(publishedReviews); }).catch(() => {}); }, []);
  return <div className="landing-page overflow-x-hidden bg-night text-[#F8FAFC]"><SeoJsonLd data={breadcrumbJsonLd([{ name: "Home", path: "/" }])} /><Navbar settings={settings} /><main><FullBleedHero settings={settings} /><Features items={settings.features} /><PlatformOverview /><HowItWorks steps={settings.howSteps} /><MarketplaceIntro settings={settings} products={products} /><Audience type="farmer" settings={settings} /><Audience type="buyer" settings={settings} /><Insights settings={settings} /><Logistics settings={settings} /><ReviewsSection reviews={reviews} /><About settings={settings} /><Contact settings={settings} /><BuiltBy developers={settings.developers} /><CTA settings={settings} /></main><Footer settings={settings} /></div>;
}
function Reveal({ children, className = "", delay = 0 }) { return <motion.div initial="hidden" whileInView="show" viewport={{ once: true, amount: 0.15 }} variants={reveal} transition={{ duration: 0.55, ease: [0.22, 1, 0.36, 1], delay }} className={className}>{children}</motion.div>; }
function Eyebrow({ children, blue = false }) { return <p className={`text-[11px] font-bold uppercase tracking-[0.2em] ${blue ? "text-[#93C5FD]" : "text-leaf"}`}>{children}</p>; }
function Media({ src, alt, className }) { if (!src) return null; return /^https?:\/\/.*\.(mp4|webm|mov)(\?.*)?$/i.test(src) ? <video src={src} className={className} controls playsInline /> : <img src={src} alt={alt} className={className} loading="lazy" />; }
function PlatformOverview() {
  const items = [
    { to: "/krishiq-ai", title: "Krishiq AI", text: "Demand forecasts, fair price signals and supplier match insights for agricultural trade." },
    { to: "/for-farmers", title: "Krishiq for Farmers", text: "List produce, manage orders, track payments and sell directly to wholesale buyers." },
    { to: "/marketplace", title: "Krishiq Marketplace", text: "Browse fresh produce lots from verified farmers and FPOs in one agricultural marketplace." },
    { to: "/agritech", title: "Krishiq Agritech", text: "Full-stack technology bringing digital listings, tracking and AI tools to modern farming." },
  ];
  return <section className="page-wrap py-16 lg:py-20"><Reveal><Eyebrow>What is Krishiq?</Eyebrow><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">An AI-powered agritech platform for farmers.</h2><p className="mt-5 max-w-2xl text-[#94A3B8]">Krishiq brings agricultural marketplace trading, farmer tools and agritech insights together so growers, FPOs and buyers can work from one unified platform.</p></Reveal><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{items.map((item, index) => <Reveal key={item.to} delay={index * 0.05}><Link to={item.to} className="landing-card block h-full border border-white/10 bg-panel p-5 transition hover:-translate-y-1"><h3 className="font-bold">{item.title}</h3><p className="mt-2 text-sm leading-relaxed text-[#94A3B8]">{item.text}</p></Link></Reveal>)}</div></section>;
}
function Features({ items = defaults.features }) { return <section className="landing-band border-y border-white/10 bg-[#081C14]"><div className="page-wrap grid grid-cols-2 divide-x divide-y divide-white/10 lg:grid-cols-4 lg:divide-y-0">{items.filter((item) => item.active !== false).map((item, index) => { const Icon = iconMap[item.icon] || [Sprout, CircleDollarSign, PackageCheck, ShieldCheck][index % 4]; return <div key={`${item.title}-${index}`} className="flex gap-3 px-3 py-5 sm:px-6 lg:py-6"><Icon className="mt-1 h-5 w-5 shrink-0 text-leaf" /><div><p className="text-sm font-bold">{item.title}</p><p className="mt-1 text-xs text-[#8EA49A]">{item.text || item.description}</p></div></div>; })}</div></section>; }
function HowItWorks({ steps = defaults.howSteps }) { return <section id="how-it-works" className="page-wrap py-16 lg:py-20"><Reveal><Eyebrow>How Krishiq Works</Eyebrow><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">A direct path from produce to purchase.</h2></Reveal><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{steps.filter((step) => step.active !== false).map((step, index) => <Reveal key={`${step.number}-${index}`} delay={index * 0.05} className="landing-card border border-white/10 bg-panel p-5"><span className="text-2xl font-black text-ai-blue">{step.number || String(index + 1).padStart(2, "0")}</span><h3 className="mt-5 font-bold">{step.title}</h3><p className="mt-2 text-sm leading-relaxed text-[#94A3B8]">{step.text || step.description}</p></Reveal>)}</div></section>; }
function MarketplaceIntro({ settings, products }) { const navigate = useNavigate(); return <section id="marketplace" className="landing-band border-y border-white/10 bg-[#071910] py-16 lg:py-20"><div className="page-wrap grid items-center gap-8 lg:grid-cols-[1fr_1.2fr]"><Reveal><Eyebrow>Krishiq Marketplace</Eyebrow><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">{settings.marketplaceHeading}</h2><p className="mt-5 max-w-xl text-[#94A3B8]">{settings.marketplaceText}</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Button onClick={() => navigate("/marketplace")}>Browse produce <ArrowRight className="h-4 w-4" /></Button><Button variant="onDark" onClick={() => navigate("/register")}>Start selling</Button></div></Reveal><Reveal delay={0.08} className="landing-card border border-white/10 bg-panel p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[0.16em] text-leaf">Live marketplace</p><h3 className="mt-2 text-xl font-bold">Find what you need</h3></div><Search className="h-5 w-5 text-[#60A5FA]" /></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{products.map((product) => <PreviewLot key={product._id} product={product} />)}{!products.length && <p className="text-sm text-[#94A3B8]">Fresh listings will appear here when sellers publish produce.</p>}</div></Reveal></div></section>; }
function PreviewLot({ product }) { const image = product.images?.[0] || product.image; return <div className="landing-card overflow-hidden border border-white/10 bg-[#0B1720]">{image ? <img src={image} alt={`${product.name} produce on Krishiq Marketplace`} className="h-28 w-full object-cover" loading="lazy" width="320" height="112" /> : <div className="grid h-28 place-items-center bg-[#123225]"><Sprout className="text-leaf" /></div>}<div className="p-3"><p className="font-bold">{product.name}</p><p className="mt-1 flex items-center gap-1 text-xs text-[#94A3B8]"><MapPin className="h-3 w-3" />{product.location || "India"}</p><p className="mt-3 text-sm font-bold text-leaf">₹{product.price} / {product.unit || "kg"}</p></div></div>; }
function Audience({ type, settings }) { const farmer = type === "farmer"; const prefix = farmer ? "farmer" : "buyer"; const bullets = settings[`${prefix}Bullets`] || []; const navigate = useNavigate(); return <section id={farmer ? "farmers" : "buyers"} className="page-wrap py-8 lg:py-12"><Reveal className={`landing-card border p-7 sm:p-9 ${farmer ? "border-leaf/30 bg-[#0A2418]" : "border-ai-blue/30 bg-[#0B1B2B]"}`}><Eyebrow blue={!farmer}>{farmer ? "Krishiq for Farmers and FPOs" : "For Buyers and Wholesale Consumers"}</Eyebrow><h2 className="mt-4 text-2xl font-black sm:text-3xl">{settings[`${prefix}Heading`]}</h2><p className="mt-3 max-w-2xl text-[#A7B8B0]">{settings[`${prefix}Text`]}</p><ul className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{bullets.map((item) => <li key={item} className="flex items-center gap-2 text-sm text-[#C7D5CE]"><Check className={farmer ? "h-4 w-4 text-leaf" : "h-4 w-4 text-[#60A5FA]"} />{item}</li>)}</ul><Button className="mt-8" variant={farmer ? "primary" : "blue"} onClick={() => navigate(settings[`${prefix}CtaLink`] || (farmer ? "/register" : "/marketplace"))}>{settings[`${prefix}CtaText`]} <ArrowRight className="h-4 w-4" /></Button></Reveal></section>; }
function Insights({ settings }) { return <section className="landing-band border-y border-white/10 bg-[#071910] py-16 lg:py-20"><div className="page-wrap grid items-center gap-8 lg:grid-cols-[0.8fr_1.2fr]"><Reveal><Eyebrow blue>Krishiq AI</Eyebrow><h2 className="mt-3 text-3xl font-black sm:text-4xl">{settings.insightsHeading}</h2><p className="mt-4 text-[#94A3B8]">{settings.insightsText}</p><Link to="/krishiq-ai" className="mt-5 inline-flex text-sm font-semibold text-leaf hover:underline">Learn about Krishiq AI</Link></Reveal><Reveal delay={0.08} className="grid gap-3 sm:grid-cols-2">{(settings.insights || []).filter((item) => item.active !== false).map((item, index) => { const Icon = iconMap[item.icon] || [Route, CircleDollarSign, Users, Truck][index % 4]; return <div key={`${item.title}-${index}`} className="landing-card flex items-center gap-3 border border-white/10 bg-panel p-5"><Icon className="h-5 w-5 text-[#60A5FA]" /><div><p className="font-bold">{item.title}</p><p className="mt-1 text-xs text-[#94A3B8]">{item.text || item.description}</p></div></div>; })}</Reveal></div></section>; }
function Logistics({ settings }) { return <section className="page-wrap py-16 lg:py-20"><Reveal><Eyebrow>From order to delivery</Eyebrow><h2 className="mt-3 text-3xl font-black sm:text-4xl">{settings.deliveryHeading}</h2></Reveal><div className="mt-9 grid gap-3 sm:grid-cols-4">{(settings.deliverySteps || []).filter((step) => step.active !== false).map((step, index) => { const Icon = [PackageCheck, Sprout, Truck, ShieldCheck][index % 4]; return <Reveal key={`${step.number}-${index}`} delay={index * 0.05} className="landing-card relative border border-white/10 bg-panel p-5"><Icon className="h-5 w-5 text-leaf" /><p className="mt-5 text-xs font-bold text-[#60A5FA]">{step.number}</p><h3 className="mt-1 font-bold">{step.title}</h3></Reveal>; })}</div></section>; }
function About({ settings }) { return <section id="about" className="landing-band border-y border-white/10 bg-[#071910] py-16 lg:py-20"><div className="page-wrap grid gap-6 lg:grid-cols-[1fr_0.8fr]"><Reveal><Eyebrow>About Krishiq</Eyebrow><h2 className="mt-3 text-3xl font-black sm:text-4xl">{settings.aboutHeading}</h2></Reveal><Reveal delay={0.08}><p className="text-[16px] leading-relaxed text-[#A7B8B0]">{settings.aboutText}</p><p className="mt-3 text-sm text-[#A7B8B0]">Krishiq is developed by Ankish to give farmers, FPOs and buyers a transparent, direct digital marketplace with AI-assisted decision tools.</p>{settings.aboutImage && <img src={settings.aboutImage} alt="About Krishiq platform" className="mt-5 h-48 w-full rounded-2xl object-cover" loading="lazy" />}<Link to="/about" className="mt-5 inline-flex text-sm font-semibold text-leaf hover:underline">Read more about Krishiq</Link></Reveal></div></section>; }
function Contact({ settings }) { if (!settings.contactEmail && !settings.contactPhone && !settings.contactAddress) return null; return <section className="page-wrap py-12"><Reveal className="border border-white/10 bg-panel p-7"><Eyebrow>Contact</Eyebrow><h2 className="mt-3 text-3xl font-black">{settings.contactHeading || "Talk to Krishiq"}</h2><div className="mt-5 flex flex-wrap gap-x-8 gap-y-2 text-sm text-[#A7B8B0]">{settings.contactEmail && <a href={`mailto:${settings.contactEmail}`}>{settings.contactEmail}</a>}{settings.contactPhone && <a href={`tel:${settings.contactPhone}`}>{settings.contactPhone}</a>}{settings.contactAddress && <span>{settings.contactAddress}</span>}</div></Reveal></section>; }
function BuiltBy({ developers = [] }) { const visible = developers.filter((developer) => developer.active !== false); if (!visible.length) return null; return <section className="page-wrap py-12"><Reveal><Eyebrow>Built By</Eyebrow><h2 className="mt-3 text-3xl font-black">Developed for a better farm-to-market journey.</h2><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{visible.map((developer, index) => <div key={`${developer.name}-${index}`} className={`landing-card border p-6 text-center transition-transform hover:-translate-y-1 ${developer.highlight ? "border-leaf/70 bg-[#0B2A1A] shadow-[0_12px_35px_rgba(34,197,94,0.14)]" : "border-white/10 bg-panel"}`}><div className="mx-auto grid h-32 w-32 place-items-center overflow-hidden rounded-full border-4 border-white/10 bg-[#123225] shadow-soft ring-4 ring-leaf/10">{developer.image ? <img src={developer.image} alt={developer.name} className="h-full w-full object-cover" /> : <span className="text-4xl font-black text-leaf/60">{developer.name?.slice(0, 1).toUpperCase() || "K"}</span>}</div><p className="mt-5 text-lg font-bold">{developer.name}</p><p className="mt-1 text-sm font-semibold text-leaf">{developer.role}</p>{developer.description && <p className="mt-3 text-sm leading-relaxed text-[#A7B8B0]">{developer.description}</p>}{developer.highlight && <span className="mt-4 inline-flex rounded-full bg-leaf/15 px-3 py-1 text-xs font-semibold text-leaf">Core team</span>}</div>)}</div></Reveal></section>; }
function CTA({ settings }) { const navigate = useNavigate(); return <section className="page-wrap py-16 lg:py-20"><Reveal><div className="landing-cta border border-leaf/30 bg-[#0B2A1A] px-6 py-12 text-center sm:px-12"><CloudSun className="mx-auto h-8 w-8 text-leaf" /><h2 className="mx-auto mt-5 max-w-2xl text-3xl font-black sm:text-5xl">{settings.ctaHeading}</h2><p className="mx-auto mt-4 max-w-xl text-[#BBD8C8]">{settings.ctaText}</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Button size="lg" variant="white" onClick={() => navigate("/register")}>Get Started <ArrowRight className="h-4 w-4" /></Button><Button size="lg" variant="onDark" onClick={() => navigate("/marketplace")}>Explore Marketplace</Button></div></div></Reveal></section>; }