import { useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import { ArrowRight, Check, CircleDollarSign, CloudSun, MapPin, PackageCheck, Route, Search, ShieldCheck, ShoppingBasket, Sparkles, Sprout, Truck, Users } from "lucide-react";
import Navbar from "../components/common/Navbar.jsx";
import Footer from "../components/common/Footer.jsx";
import BrandLogo from "../components/common/BrandLogo.jsx";
import HeroSlider from "../components/common/HeroSlider.jsx";
import { Button } from "../components/common/ui.jsx";

const reveal = { hidden: { opacity: 0, y: 18 }, show: { opacity: 1, y: 0 } };
const transition = { duration: 0.55, ease: [0.22, 1, 0.36, 1] };

export default function Home() {
  return <div className="landing-page overflow-x-hidden bg-night text-[#F8FAFC]"><Navbar /><Hero /><TrustStrip /><HowItWorks /><MarketplaceIntro /><Audience /><Insights /><Logistics /><About /><CTA /><Footer /></div>;
}

function Reveal({ children, className = "", delay = 0 }) {
  return <motion.div initial="hidden" whileInView="show" viewport={{ once: true, amount: 0.15 }} variants={reveal} transition={{ ...transition, delay }} className={className}>{children}</motion.div>;
}

function Eyebrow({ children, blue = false }) { return <p className={`text-[11px] font-bold uppercase tracking-[0.2em] ${blue ? "text-[#93C5FD]" : "text-leaf"}`}>{children}</p>; }

function Hero() {
  const navigate = useNavigate();
  return <section className="relative overflow-hidden pt-[76px]"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_12%_12%,rgba(34,197,94,0.14),transparent_32%),radial-gradient(circle_at_88%_10%,rgba(37,99,235,0.12),transparent_30%)]" /><div className="page-wrap relative grid items-center gap-10 py-14 lg:grid-cols-[0.9fr_1.1fr] lg:py-20"><Reveal><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-leaf/20 bg-leaf/10 px-3 py-1.5 text-[11px] font-bold uppercase tracking-[0.15em] text-leaf"><Sparkles className="h-3.5 w-3.5" /> Direct farm-to-market platform</div><h1 className="max-w-2xl text-[44px] font-black leading-[1.03] tracking-[-0.04em] sm:text-6xl lg:text-[68px]">From Farm to Market.<span className="mt-3 block"><span className="text-leaf">Smarter.</span> <span className="text-[#60A5FA]">Direct.</span> <span className="text-leaf">Fair.</span></span></h1><p className="mt-6 max-w-xl text-[16px] leading-relaxed text-[#A7B8B0] sm:text-[18px]">KRISHIQ connects farmers and buyers directly, making agricultural trade more transparent, accessible and efficient.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button size="lg" className="w-full sm:w-auto" onClick={() => navigate("/register")}>Get Started <ArrowRight className="h-4 w-4" /></Button><Button size="lg" variant="onDark" className="w-full sm:w-auto" onClick={() => navigate("/marketplace")}>Explore Marketplace</Button></div><div className="mt-8 flex items-center gap-3 text-sm text-[#94A3B8]"><BrandLogo className="h-10 w-10" /><span>Built to simplify the journey from produce to purchase.</span></div></Reveal><Reveal delay={0.1}><HeroSlider /></Reveal></div></section>;
}

function TrustStrip() {
  const items = [[Sprout, "Fresh listings", "From farms and FPOs"], [CircleDollarSign, "Clear pricing", "Compare before ordering"], [PackageCheck, "Order visibility", "Track each handoff"], [ShieldCheck, "Secure by design", "Payment-ready checkout"]];
  return <section className="landing-band border-y border-white/10 bg-[#081C14]"><div className="page-wrap grid grid-cols-2 divide-x divide-y divide-white/10 lg:grid-cols-4 lg:divide-y-0">{items.map(([Icon, title, text]) => <div key={title} className="flex gap-3 px-3 py-5 sm:px-6 lg:py-6"><Icon className="mt-1 h-5 w-5 shrink-0 text-leaf" /><div><p className="text-sm font-bold">{title}</p><p className="mt-1 text-xs text-[#8EA49A]">{text}</p></div></div>)}</div></section>;
}

function HowItWorks() {
  const steps = [["01", "Create your account", "Join as a farmer, FPO or buyer."], ["02", "List or discover produce", "Share supply or find the right listing."], ["03", "Connect and place order", "Agree on quantity, price and delivery."], ["04", "Get produce delivered", "Follow the order from pickup to arrival."]];
  return <section id="how-it-works" className="page-wrap py-16 lg:py-20"><Reveal><Eyebrow>How KRISHIQ works</Eyebrow><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">A direct path from produce to purchase.</h2></Reveal><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{steps.map(([number, title, text], index) => <Reveal key={number} delay={index * 0.05} className="landing-card border border-white/10 bg-panel p-5"><span className="text-2xl font-black text-ai-blue">{number}</span><h3 className="mt-5 font-bold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-[#94A3B8]">{text}</p></Reveal>)}</div></section>;
}

function MarketplaceIntro() {
  const navigate = useNavigate();
  return <section id="marketplace" className="landing-band border-y border-white/10 bg-[#071910] py-16 lg:py-20"><div className="page-wrap grid items-center gap-8 lg:grid-cols-[1fr_1.2fr]"><Reveal><Eyebrow>Marketplace</Eyebrow><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">Explore fresh produce directly from the source.</h2><p className="mt-5 max-w-xl text-[#94A3B8]">Search crops, compare available lots, review seller details and place an order from one straightforward marketplace.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Button onClick={() => navigate("/marketplace")}>Browse produce <ArrowRight className="h-4 w-4" /></Button><Button variant="onDark" onClick={() => navigate("/register")}>Start selling</Button></div></Reveal><Reveal delay={0.08} className="landing-card border border-white/10 bg-panel p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[0.16em] text-leaf">Marketplace preview</p><h3 className="mt-2 text-xl font-bold">Find what you need</h3></div><Search className="h-5 w-5 text-[#60A5FA]" /></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><PreviewLot name="Tomato" location="Jaipur" price="₹28 / kg" image="https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80" /><PreviewLot name="Onion" location="Kota" price="₹22 / kg" image="https://images.unsplash.com/photo-1508747703725-619778acdf10?auto=format&fit=crop&w=600&q=80" /><PreviewLot name="Wheat" location="Alwar" price="₹26 / kg" image="https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80" /></div></Reveal></div></section>;
}

function PreviewLot({ name, location, price, image }) { return <div className="landing-card overflow-hidden border border-white/10 bg-[#0B1720]"><img src={image} alt={`${name} produce`} loading="lazy" className="h-28 w-full object-cover" /><div className="p-3"><p className="font-bold">{name}</p><p className="mt-1 flex items-center gap-1 text-xs text-[#94A3B8]"><MapPin className="h-3 w-3" />{location}</p><p className="mt-3 text-sm font-bold text-leaf">{price}</p><p className="mt-1 text-[11px] text-[#94A3B8]">Seller details available</p></div></div>; }

function Audience() {
  const navigate = useNavigate();
  const groups = [["farmers", "For farmers and FPOs", "Sell directly. Reach more buyers.", ["List your produce", "Manage orders", "View market prices", "Manage deliveries"], "Start Selling", "green"], ["buyers", "For buyers and consumers", "Source directly from the farm.", ["Discover fresh produce", "Compare listings", "Buy required quantities", "Track deliveries"], "Explore Produce", "blue"]];
  return <section className="page-wrap grid gap-5 py-16 lg:grid-cols-2 lg:py-20">{groups.map(([id, eyebrow, title, items, cta, tone], index) => <Reveal key={id} delay={index * 0.08} className={`landing-card border p-7 sm:p-9 ${tone === "green" ? "border-leaf/30 bg-[#0A2418]" : "border-ai-blue/30 bg-[#0B1B2B]"}`}><div id={id} className="scroll-mt-24"><Eyebrow blue={tone === "blue"}>{eyebrow}</Eyebrow><h2 className="mt-4 text-2xl font-black sm:text-3xl">{title}</h2><ul className="mt-6 grid gap-3 sm:grid-cols-2">{items.map((item) => <li key={item} className="flex items-center gap-2 text-sm text-[#C7D5CE]"><Check className={`h-4 w-4 ${tone === "green" ? "text-leaf" : "text-[#60A5FA]"}`} />{item}</li>)}</ul><Button className="mt-8" variant={tone === "green" ? "primary" : "blue"} onClick={() => navigate("/register")}>{cta} <ArrowRight className="h-4 w-4" /></Button></div></Reveal>)}</section>;
}

function Insights() { return <section className="landing-band border-y border-white/10 bg-[#071910] py-16 lg:py-20"><div className="page-wrap grid items-center gap-8 lg:grid-cols-[0.8fr_1.2fr]"><Reveal><Eyebrow blue>Smart insights</Eyebrow><h2 className="mt-3 text-3xl font-black sm:text-4xl">Useful signals, when live market data is connected.</h2><p className="mt-4 text-[#94A3B8]">KRISHIQ can help users understand demand trends, price trends, suitable connections and delivery options. This preview stays intentionally data-light until live sources are connected.</p></Reveal><Reveal delay={0.08} className="grid gap-3 sm:grid-cols-2"><Insight title="Demand trends" icon={Route} /><Insight title="Price trends" icon={CircleDollarSign} /><Insight title="Suitable connections" icon={Users} /><Insight title="Delivery optimization" icon={Truck} /></Reveal></div></section>; }
function Insight({ title, icon: Icon }) { return <div className="landing-card flex items-center gap-3 border border-white/10 bg-panel p-5"><Icon className="h-5 w-5 text-[#60A5FA]" /><div><p className="font-bold">{title}</p><p className="mt-1 text-xs text-[#94A3B8]">Insights preview · live data pending</p></div></div>; }

function Logistics() { return <section className="page-wrap py-16 lg:py-20"><Reveal><Eyebrow>From order to delivery</Eyebrow><h2 className="mt-3 text-3xl font-black sm:text-4xl">Every handoff stays visible.</h2></Reveal><div className="mt-9 grid gap-3 sm:grid-cols-4">{[["01", "Order confirmed", PackageCheck], ["02", "Pickup scheduled", Sprout], ["03", "In transit", Truck], ["04", "Delivered", ShieldCheck]].map(([number, title, Icon], index) => <Reveal key={number} delay={index * 0.05} className="landing-card relative border border-white/10 bg-panel p-5"><Icon className="h-5 w-5 text-leaf" /><p className="mt-5 text-xs font-bold text-[#60A5FA]">{number}</p><h3 className="mt-1 font-bold">{title}</h3>{index < 3 && <ArrowRight className="absolute -right-3 top-1/2 z-10 hidden h-5 w-5 -translate-y-1/2 text-[#5B7668] sm:block" />}</Reveal>)}</div></section>; }

function About() { return <section id="about" className="landing-band border-y border-white/10 bg-[#071910] py-16 lg:py-20"><div className="page-wrap grid gap-6 lg:grid-cols-[1fr_0.8fr]"><Reveal><Eyebrow>About KRISHIQ</Eyebrow><h2 className="mt-3 text-3xl font-black sm:text-4xl">Connecting farms with markets.</h2></Reveal><Reveal delay={0.08}><p className="text-[16px] leading-relaxed text-[#A7B8B0]">KRISHIQ is building a more direct and transparent agricultural marketplace where farmers, FPOs and buyers can connect through one digital platform.</p></Reveal></div></section>; }
function CTA() { const navigate = useNavigate(); return <section className="page-wrap py-16 lg:py-20"><Reveal><div className="landing-cta border border-leaf/30 bg-[#0B2A1A] px-6 py-12 text-center sm:px-12"><CloudSun className="mx-auto h-8 w-8 text-leaf" /><h2 className="mx-auto mt-5 max-w-2xl text-3xl font-black sm:text-5xl">Make the next market decision simpler.</h2><p className="mx-auto mt-4 max-w-xl text-[#BBD8C8]">Join a direct, transparent marketplace for agricultural trade.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Button size="lg" variant="white" onClick={() => navigate("/register")}>Get Started <ArrowRight className="h-4 w-4" /></Button><Button size="lg" variant="onDark" onClick={() => navigate("/marketplace")}>Explore Marketplace</Button></div></div></Reveal></section>; }
